### ISSUE TITLE
Umstellung auf "YForm ohne Plugins"

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/yform_adminer#26]
Nach ersten Tests sind nur Änderungen in der **package.yml** erforderlich:

```yml
version: '1.5.0'                   => Wegen Inkomtatibilität/BC auf 2.0 ändern
requires:
    redaxo: '^5.15.0'              => Wenn YForm eine spätere Version benötigt, darauf ändern
    packages:
        yform: '^4.0.0'            => YForm-Versionsnummer
        yform/manager: '^4.0.0'.   => entfernen
```
